# SSH key setup
- name: Add the SSH key
  register: the_key
  digital_ocean:
    command: ssh
    state: present
    name: https-terminator admin key
    ssh_pub_key: "{{ lookup('file', 'keys/admin.pub') }}"
    api_token: "{{ token }}"
# Set up the host.
- name: Create the host
  register: the_host
  digital_ocean:
    command: droplet
    name: https-terminator
    state: present
    size_id: 512mb
    # Use Ubuntu as a base because it has all the things we need and is generally trustworthy.
    image_id: ubuntu-16-04-x64
    # Using a German host to respect our users.
    region_id: fra1
    private_networking: yes
    ssh_key_ids: "{{ the_key.ssh_key.id }}"
    unique_name: yes
    api_token: "{{ token }}"
- name: Add the host to inventory
  when: the_host.droplet is defined
  add_host:
    name: "{{ the_host.droplet.ip_address }}"
    groups: the_host
